config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :requests, only: [:create, :new, :index]

  resources :saves
  resources :searches, only: [:index]

  root 'requests#new'

  get '/results/:id' => 'pages#results'
  get '/results/:id/page/:pagenum' => 'pages#paginate_results'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name ="viewport" content="width=device-width, initial-scale=1">
  <title>Reading History</title>
  <!--Bootstrap -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
	<ul class="nav navbar-nav navbar-left">
		<% if user_signed_in? %>
			<li><%= link_to "Home" ,  root_path %></li>
			<li><%= link_to "Settings" ,  edit_user_registration_path %></li>
			<li><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>
			<li><%= link_to "Saves" , saves_path %></li>
			<li><%= link_to "Recent Searches" , searches_path %></li>
		<% else %>
			<li><%= link_to "Home" ,  root_path %></li>
			<li><%= link_to "Sign Up" , new_user_registration_path %></li>
			<li><%= link_to "Log In" , new_user_session_path %></li>
		<% end %>
	</ul>
</nav>

<!-- flash messages for devise -->
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="main-container" class="container">
<%= yield %>
</div>

</body>
</html>